# Generated by Django 2.1.7 on 2023-08-29 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230829_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 29, 18, 7, 40, 372289)),
        ),
    ]
